### ISSUE TITLE
rosprolog_client library is not exported

### ISSUE THREAD

**Issue by bbferka** [daniel86/knowrob#22]
Hey Daniel, 

I'm using your fork. In the CMake of rosprolog you forgot to export the rosprolog_client library.  Should be like below. 

```
catkin_package(
  LIBRARIES rosprolog rosprolog_client
  INCLUDE_DIRS include 
  CATKIN_DEPENDS json_prolog_msgs geometry_msgs roscpp roslib rospack
)
```

Any timeline for when this new C++ based interface is going to be in the main repo?

**Comment by daniel86** [comment]
Hola amigo,

thanks for the report! Yes seems I forgot it.
The client has still this nasty json-glib-1.0 dependency, I hope to get rid of it soon :/

regarding the main repo, please have a look at the master branch. The C++ rosprolog node is already there!
But I recently fixed some remaining bugs with the object-state-publisher, I'll merge latest tomorrow.
